language: python
python:
- '2.7'
# Cache our Gcloud SDK between commands
cache:
  directories:
  - $HOME/google-cloud-sdk/
env:
# Make sure gcloud command is on our PATH and the App Engine SDK is in the Python path
- GAE_PYTHONPATH=${HOME}/.cache/google_appengine PATH=$PATH:${HOME}/google-cloud-sdk/bin PYTHONPATH=${PYTHONPATH}:${GAE_PYTHONPATH} CLOUDSDK_CORE_DISABLE_PROMPTS=1
services:
# Start elasticsearch server on 9200 port to unittest
- elasticsearch
before_install:
- echo "HOME =>"
- echo $HOME
# Install Google App Engine Python SDK
- if [ ! -d "${GAE_PYTHONPATH}" ]; then
    python tools/scripts/fetch_gae_sdk.py $(dirname "${GAE_PYTHONPATH}");
  fi
# If the SDK is not already cached, download it and unpack it
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
# Add gcloud to $PATH
- source /home/travis/google-cloud-sdk/path.bash.inc
# Decrypt the credentials we added to the repo using the key we added with the Travis command line tool
- openssl aes-256-cbc -K $encrypted_637db9bb9740_key -iv $encrypted_637db9bb9740_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz
# Env file was stored on credentials.tar.gz.enc. We need to move it for app/ directory
- mv .env app/
# Prepare files for unittest
- mkdir $HOME/.resources
- mv knowledgemap_service_account.json $HOME/.resources/
# Here we use the decrypted service account credentials to authenticate the command line tool
- gcloud auth activate-service-account --key-file service_account_secret.json
install:
# Install the Python dependencies for unittest and app
- pip install -r requirements_test.txt -t lib_tests
- pip install -r app/requirements.txt -t app/lib/
# Set the correct project to deploy to
- gcloud config set project stack-ciandt
- gcloud -q components update gae-python
before_script:
- sleep 10
script:
# print tool versions for debug
- gcloud version
- python --version
# Run the unit tests
- nosetests -v --nocapture --nologcapture tests
# - gcloud app deploy -v integration --promote
# test end_2_end.py
after_success:
# replace version control with TRAVIS_BUILD_NUMBER env
- sed -i bak -e "s/BUILD_NUMBER/$TRAVIS_BUILD_NUMBER/g" app/backend/version.py
# Deploy the app
- cd app/
- gcloud app deploy -v production --promote --verbosity=info
