language: python
python:
- '2.7'
# elasticsearch-service is used for unittests
services:
- elasticsearch
before_script:
- sleep 15
install:
- pip install -r requirements_test.txt -t lib_tests
script:
- python --version
- nosetests -v --nocapture --nologcapture tests
