profile:
  elasticsearch:
    host: http://localhost:9200
    user:
    pass:

knowledge:
  elasticsearch:
    host: http://localhost:9200
    user:
    pass:

project:
  elasticsearch:
    host: http://localhost:9200
    user:
    pass:

skill:
  elasticsearch:
    host: http://localhost:9200
    user:
    pass:

stack:
  elasticsearch:
    host: http://localhost:9200
    user:
    pass:

techgallery:
  endpoint: https://tech-gallery.appspot.com/_ah/api/rest/v1
  auth: true
