version: '2'
services:
    stack-elasticsearch:
        image: elasticsearch:2.4.3
        # ports:
        # uncomment if you don't use nginx proxy
        #     - "9300:9300"
        #     - "9200:9200"
        # # uncomment this section to have elasticsearch data persisted to a volume
        # volumes:
        #   - /home/stack/data:/usr/share/elasticsearch/data
    stack-kibana:
        build: kibana/
        depends_on:
            - stack-elasticsearch
        # ports:
        # # uncomment if you don't use nginx proxy
        #     - "5601:5601"
        # environment:
            # - ELASTICSEARCH_URL=http://stack-elasticsearch:9200
        volumes:
            - ./conf/kibana/kibana.yml:/opt/kibana/config/kibana.yml
    stack-nginx:
       image: nginx:1.11.8
       depends_on:
           - stack-elasticsearch
           - stack-kibana
       ports:
           - "80:80"
           - "9200:9200"
       volumes:
           # uncomment if you enable auth_basic on nginx para
           # elasticsearch or kibana services
           # - ./conf/nginx/.htpasswd:/etc/nginx/.htpasswd
           - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
